/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Articel: typeof import('./components/Articel.vue')['default']
    ButtonButton: typeof import('./components/button/Button.vue')['default']
    ButtonList: typeof import('./components/ButtonList.vue')['default']
    Column: typeof import('./components/Column.vue')['default']
    DesktopDNav: typeof import('./components/desktop/DNav.vue')['default']
    DesktopDTopBar: typeof import('./components/desktop/DTopBar.vue')['default']
    MarketType: typeof import('./components/MarketType.vue')['default']
    MobileMNav: typeof import('./components/mobile/MNav.vue')['default']
    MobileMTopBar: typeof import('./components/mobile/MTopBar.vue')['default']
    MonthYearPicker: typeof import('./components/MonthYearPicker.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    Sector: typeof import('./components/Sector.vue')['default']
    Stock: typeof import('./components/Stock.vue')['default']
    TR: typeof import('./components/TR.vue')['default']
  }
}
